# Generated by Django 3.1.1 on 2020-09-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва страви')),
                ('price', models.IntegerField(verbose_name='Ціна страви')),
                ('description', models.TextField(max_length=250, verbose_name='Опис страви')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('food_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.foodtype')),
            ],
        ),
    ]
