# Generated by Django 3.1.1 on 2020-09-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тип страви'),
        ),
    ]
