# Generated by Django 3.1.1 on 2020-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200908_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Тип страви'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
