# Generated by Django 3.1.1 on 2020-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sushi_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва страви')),
                ('price', models.IntegerField(verbose_name='Ціна страви')),
                ('description', models.TextField(max_length=250, verbose_name='Опис страви')),
                ('image', models.ImageField(upload_to='New/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'New',
            },
        ),
        migrations.RemoveField(
            model_name='sushi',
            name='new',
        ),
    ]
