# Generated by Django 3.1.1 on 2020-09-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200912_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': '1. New Dishes', 'verbose_name_plural': '1. New Dishes'},
        ),
    ]
