# Generated by Django 3.1.1 on 2020-10-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201002_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m/%d/'),
        ),
    ]
