# Generated by Django 3.1.1 on 2020-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
